BINANCE_API = 'https://api.binance.com'
BINANCE_API1 = 'https://api1.binance.com'
BINANCE_API2 = 'https://api2.binance.com'
BINANCE_API3 = 'https://api3.binance.com'
BINANCE_API4 = 'https://api4.binance.com'