BINACNE_API = 'https://api.binance.com'
BINACNE_API1 = 'https://api1.binance.com'
BINACNE_API2 = 'https://api2.binance.com'
BINACNE_API3 = 'https://api3.binance.com'
BINACNE_API4 = 'https://api4.binance.com'