BACKEND_SERVER_PORT = 8000
BACKEND_SERVER_IP = "127.0.0.1"
BACKEND_SERVER_HTTP_PROTOCOL = "http"

BACKEND_SERVER_ADDRESS = f'{BACKEND_SERVER_HTTP_PROTOCOL}://{BACKEND_SERVER_IP}:{BACKEND_SERVER_PORT}'