import streamlit as st
from frontend.src.library.ui_elements import fix_page_layout
from frontend.src.library.analytics_helper.client import fetch_available_coins


fix_page_layout('🔮 forecasting')
st.markdown("""<h2 style='text-align: center;margin-top:0; padding-top:0;'>Crypto Analysis & Forecasting</h2>""", unsafe_allow_html=True)

# st.markdown("""<h5 style='text-align: left;margin-top:0; padding-top:0;'>Crypto Analysis</h5>""",
#             unsafe_allow_html=True)
st.write(
    "The **Oracle** 🔮 algorithm will the coin's price history data along with exogenous factors which are correlated and affect the overall crypto market in combination with features generated by **NLP** 🕵🏻 to assess the overall sentiment of the market through latest news (Websites, tweets etc.)")

st.markdown("""<h5 style='text-align: left;margin-top:0; padding-top:0;'>Crypto Analysis</h5>""", unsafe_allow_html=True)
with st.form(key='forecasting_form', border=True):
    cols = st.columns(3)
    with cols[0]:
        coin = st.selectbox(label='Choose Coin', options=fetch_available_coins())
    with cols[1]:
        time_int = st.selectbox(
            'Choose Date Interval',
            ('1m', '5m', '15m', '30m', '1h', '4h', '12h', '1d', '3d', '1w', '1M'))
    with cols[2]:
        time_limit = st.number_input('Choose Sample Limit', value=500, min_value=2, max_value=1000000)

    plot_type = st.radio('Plot type', options=['Line Plot', 'Candle Plot'], index=0, horizontal=True)

    sumbit_button = st.form_submit_button('Summon the Oracle 🔮')
    if sumbit_button:
        st.write('AAA')
