import streamlit as st
from frontend.src.library.ui_elements import fix_page_layout
from frontend.src.library.analytics_helper.client import fetch_available_coins
from frontend.src.library.analytics_helper.plots import price_history_plot
from frontend.src.library.overview_helper.navigation import api_status_check

fix_page_layout('🔮 forecasting')
st.html("""<h2 style='text-align: center;margin-top:0; padding-top:0;'>Crypto Analysis & Forecasting</h2>""")

st.write(
    "The **Oracle** 🔮 algorithm will use the coin's price history data along with exogenous factors which are correlated and affect the overall crypto market in combination with features generated by **NLP** 🕵🏻 to assess the overall sentiment of the market through latest news (Websites, tweets etc.) to **forecast** the Coin's future price.")


if "available_exchange_apis" not in st.session_state:
    with st.spinner("Checking API Availability Status..."):
        api_status_check()

st.write("TBD")
