# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"8\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\ninput_text\x18\x02 \x01(\t\"&\n\x0fPredictResponse\x12\x13\n\x0boutput_text\x18\x01 \x01(\t\"w\n\x0c\x41gentRequest\x12\x13\n\x0b\x61pplication\x18\x01 \x01(\t\x12\x12\n\nmodel_type\x18\x02 \x01(\t\x12\x16\n\x0emodel_provider\x18\x03 \x01(\t\x12\x12\n\nmodel_name\x18\x04 \x01(\t\x12\x12\n\ninput_text\x18\x05 \x01(\t\"=\n\rAgentResponse\x12\x13\n\x0boutput_text\x18\x01 \x01(\t\x12\x17\n\x0foutput_metadata\x18\x02 \x01(\t2\x97\x01\n\x10InferenceService\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\x12\x41\n\x0c\x41gentExecute\x12\x17.inference.AgentRequest\x1a\x18.inference.AgentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=30
  _globals['_PREDICTREQUEST']._serialized_end=86
  _globals['_PREDICTRESPONSE']._serialized_start=88
  _globals['_PREDICTRESPONSE']._serialized_end=126
  _globals['_AGENTREQUEST']._serialized_start=128
  _globals['_AGENTREQUEST']._serialized_end=247
  _globals['_AGENTRESPONSE']._serialized_start=249
  _globals['_AGENTRESPONSE']._serialized_end=310
  _globals['_INFERENCESERVICE']._serialized_start=313
  _globals['_INFERENCESERVICE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
